<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:s="http://www.sitemaps.org/schemas/sitemap/0.9">
<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes" omit-xml-declaration="yes"/>
<xsl:template match="/">
  <html lang="en">
  <head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>Jounee · Sitemap</title>
    <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&amp;family=DM+Sans:wght@400;500;600&amp;display=swap" rel="stylesheet"/>
    <style>
      *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
      body { font-family: 'DM Sans', sans-serif; background: #F7F5F2; color: #1A1714; padding: 48px 24px; min-height: 100vh; line-height: 1.55; -webkit-font-smoothing: antialiased; }
      .wrap { max-width: 960px; margin: 0 auto; }
      header { display: flex; align-items: center; gap: 14px; padding-bottom: 24px; border-bottom: 1px solid #E8E4DF; margin-bottom: 32px; }
      .logo { font-family: 'DM Serif Display', serif; font-size: 24px; line-height: 1; color: #1A1714; text-decoration: none; }
      .logo .nee { color: #2D6A4F; font-style: italic; }
      h1 { font-family: 'DM Serif Display', serif; font-weight: 400; font-size: 36px; line-height: 1.15; letter-spacing: -0.01em; margin-bottom: 10px; }
      .lede { color: #7A7470; font-size: 15px; margin-bottom: 32px; }
      .lede strong { color: #1A1714; font-weight: 600; }
      table { width: 100%; border-collapse: collapse; background: #FFFFFF; border: 1px solid #E8E4DF; border-radius: 16px; overflow: hidden; }
      thead th { background: #FAF9F7; font-size: 11px; font-weight: 600; color: #7A7470; letter-spacing: 0.08em; text-transform: uppercase; text-align: left; padding: 14px 20px; border-bottom: 1px solid #E8E4DF; }
      thead th.num { text-align: right; }
      tbody td { padding: 16px 20px; font-size: 14px; border-bottom: 1px solid #F2EFEA; vertical-align: middle; }
      tbody tr:last-child td { border-bottom: none; }
      tbody tr:hover { background: #FBFAF7; }
      tbody a { color: #2D6A4F; text-decoration: none; font-weight: 500; word-break: break-all; }
      tbody a:hover { text-decoration: underline; }
      .num { text-align: right; font-variant-numeric: tabular-nums; color: #7A7470; }
      .freq { color: #7A7470; text-transform: capitalize; }
      footer { margin-top: 32px; font-size: 12px; color: #7A7470; text-align: center; }
      footer a { color: #7A7470; }
      @media (max-width: 600px) {
        body { padding: 28px 16px; }
        h1 { font-size: 28px; }
        thead th, tbody td { padding: 12px 14px; font-size: 13px; }
      }
    </style>
  </head>
  <body>
    <div class="wrap">
      <header>
        <a class="logo" href="/">Jou<span class="nee">nee</span></a>
      </header>
      <h1>Sitemap</h1>
      <p class="lede">
        Every URL on Jounee available to search engines.
        Total: <strong><xsl:value-of select="count(s:urlset/s:url)"/></strong>
        URL<xsl:if test="count(s:urlset/s:url) != 1">s</xsl:if>.
      </p>
      <table>
        <thead>
          <tr>
            <th>URL</th>
            <th class="num">Priority</th>
            <th>Frequency</th>
          </tr>
        </thead>
        <tbody>
          <xsl:for-each select="s:urlset/s:url">
            <xsl:sort select="s:priority" order="descending" data-type="number"/>
            <tr>
              <td>
                <a>
                  <xsl:attribute name="href"><xsl:value-of select="s:loc"/></xsl:attribute>
                  <xsl:value-of select="s:loc"/>
                </a>
              </td>
              <td class="num"><xsl:value-of select="s:priority"/></td>
              <td class="freq"><xsl:value-of select="s:changefreq"/></td>
            </tr>
          </xsl:for-each>
        </tbody>
      </table>
      <footer>
        <p>Generated by Jounee · <a href="/">jounee.app</a></p>
      </footer>
    </div>
  </body>
  </html>
</xsl:template>
</xsl:stylesheet>
